name: Python Package using Conda

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          activate-environment: base

      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda env update --file environment.yml --name base --prune

      - name: Upgrade build tools
        shell: bash -el {0}
        run: python -m pip install --upgrade pip setuptools wheel build

      - name: Build package
        shell: bash -el {0}
        run: python -m build --sdist --wheel .

      - name: Lint with flake8
        shell: bash -el {0}
        run: |
          conda install flake8 -y
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        shell: bash -el {0}
        run: |
          conda install pytest -y
          pytest --verbose
